database:
  showSql: @dbShowSql@

server:
  port: 8090

eureka:
  instance:
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: http://admin:BdEwu2023@localhost:8082/eureka/

spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/lims
    username: root
    password: root
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    show-sql: ${database.showSql}
    properties:
      hibernate:
        format_sql: ${database.showSql}
